# Germany Municipalities - Sample Notebook

## Explore data

In [1]:

import pandas as pd        

# Read csv file
dataframe = pd.read_csv("./data/03-gold/germany-municipalities-2026-03-csv/germany-municipalities-2026-03-municipalities.csv")

In [2]:

# Display 5 first rows
dataframe.head()

,ars,ags,type,sub_type,municipality_name,area_sqkm,population_total,population_male,population_female,population_per_sqkm,zip_code,center_lon,center_lat,degree_of_urbanization_key,degree_of_urbanization_name
0,10010000000,1001000,municipality,independent_city_duplicate,"Flensburg, Stadt",56.73,96326,47651,48675,1698,24937.0,"9,43751","54,78252",1.0,dicht besiedelt
1,10020000000,1002000,municipality,independent_city_duplicate,"Kiel, Landeshauptstadt",118.65,252668,123532,129136,2130,24103.0,"10,13727","54,321775",1.0,dicht besiedelt
2,10030000000,1003000,municipality,independent_city_duplicate,"Lübeck, Hansestadt",214.19,216889,104309,112580,1013,23539.0,"10,683932","53,866269",1.0,dicht besiedelt
3,10040000000,1004000,municipality,independent_city_duplicate,"Neumünster, Stadt",71.66,79809,39742,40067,1114,24534.0,"9,988422","54,069895",1.0,dicht besiedelt
4,10510011011,1051011,municipality,city,"Brunsbüttel, Stadt",65.21,12692,6419,6273,195,25541.0,"9,13735","53,896932",2.0,mittlere Besiedlungsdichte

In [3]:

# Display dataframe info
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 10943 entries, 0 to 10942
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ars                          10943 non-null  int64
 1   ags                          10943 non-null  int64
 2   type                         10943 non-null  str
 3   sub_type                     10943 non-null  str
 4   municipality_name            10943 non-null  str
 5   area_sqkm                    10943 non-null  float64
 6   population_total             10943 non-null  int64
 7   population_male              10943 non-null  int64
 8   population_female            10943 non-null  int64
 9   population_per_sqkm          10943 non-null  int64
 10  zip_code                     10751 non-null  float64
 11  center_lon                   10940 non-null  str
 12  center_lat                   10940 non-null  str
 13  degree_of_urbanization_key   10942 non-null  float64
 14  degree_of_urbanization_name  10942 non-null  str
dtypes: float64(3), int64(6), str(6)
memory usage: 2.1 MB

In [4]:

# Describe dataframe
dataframe.describe()

,ars,ags,area_sqkm,population_total,population_male,population_female,population_per_sqkm,zip_code,degree_of_urbanization_key
count,1.094300e+04,1.094300e+04,10943.000000,1.094300e+04,1.094300e+04,1.094300e+04,10943.000000,10751.000000,10942.000000
mean,8.235411e+10,8.235133e+06,32.686096,7.637498e+03,3.768775e+03,3.868723e+03,186.620488,52431.387964,2.712301
std,4.027390e+10,4.027441e+06,41.244369,5.018875e+04,2.463676e+04,2.555349e+04,290.771239,29095.625813,0.481665
min,1.001000e+10,1.001000e+06,0.310000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1067.000000,1.000000
25%,6.535000e+10,6.535002e+06,8.360000,6.190000e+02,3.100000e+02,3.080000e+02,49.000000,24872.500000,2.000000
50%,8.128014e+10,8.128047e+06,19.090000,1.750000e+03,8.790000e+02,8.700000e+02,94.000000,55413.000000,3.000000
75%,9.772019e+10,9.772150e+06,40.805000,5.489500e+03,2.726500e+03,2.759000e+03,194.000000,78241.500000,3.000000
max,1.607751e+11,1.607705e+07,891.120000,3.685265e+06,1.810259e+06,1.875006e+06,4844.000000,99998.000000,3.000000